services:
  # 1. Nuestro servicio de Backend (la API FastAPI y el Agente de IA)
  backend:
    # Construye la imagen usando el Dockerfile de la raíz del proyecto
    build: .
    container_name: insurance_chatbot_api
    ports:
      # Expone el puerto 8000 de la API a tu máquina local
      - "8000:8000"
    env_file:
      - .env # Carga las variables de entorno
    volumes:
      # Montamos las carpetas de código para ver los cambios en tiempo real
      - ./app:/code/app
      - ./scripts:/code/scripts
      - ./data:/code/data
    depends_on:
      chromadb:
        # El backend no arrancará hasta que ChromaDB esté listo y saludable
        condition: service_started

  # 2. Nuestro servicio de Base de Datos Vectorial
  chromadb:
    image: ghcr.io/chroma-core/chroma
    container_name: insurance_chromadb
    ports:
      # Expone el puerto de la API de Chroma al 8001 de tu máquina
      - "8001:8000"
    volumes:
      # ¡IMPORTANTE! Persistimos los datos de la base de datos en nuestra carpeta local
      - ./data_store/chroma_seguros:/chroma/

